# Generated by Django 3.2.15 on 2022-10-13 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('conducted_by', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('dashboard', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.dashboard')),
            ],
        ),
    ]
