# Generated by Django 3.2.15 on 2022-10-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='explore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('organized_by', models.CharField(max_length=30)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('Venue', models.CharField(max_length=20)),
                ('theme', models.CharField(max_length=50)),
                ('rules', models.CharField(max_length=100)),
                ('event_details', models.CharField(max_length=300)),
                ('rewards', models.CharField(max_length=100)),
                ('other_details', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_num', models.CharField(max_length=10)),
                ('main_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.main')),
            ],
        ),
    ]
