# Generated by Django 3.2.16 on 2022-10-28 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_explore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explore',
            name='Venue',
        ),
        migrations.RemoveField(
            model_name='explore',
            name='event_details',
        ),
        migrations.RemoveField(
            model_name='explore',
            name='other_details',
        ),
        migrations.RemoveField(
            model_name='explore',
            name='theme',
        ),
        migrations.AddField(
            model_name='explore',
            name='OD',
            field=models.CharField(choices=[('OD', 'OD will be Provided'), ('NOOD', 'OD will not be Provided')], default='NOOD', max_length=4, verbose_name='Info about OD'),
        ),
        migrations.AddField(
            model_name='explore',
            name='description',
            field=models.TextField(default='NULL', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='explore',
            name='participants',
            field=models.CharField(choices=[('IE', 'Interdepartmental'), ('IA', 'Intradepartmental')], default='IA', max_length=2, verbose_name='Inter or Intra'),
        ),
        migrations.AddField(
            model_name='explore',
            name='participation_type',
            field=models.CharField(choices=[('I', 'Individual'), ('T2', 'Team size-2'), ('T3', 'Team size-3'), ('T4', 'Team size-4'), ('T5', 'Team size-5'), ('T6', 'Team size-6')], default='I', max_length=2, verbose_name='Type of Participation'),
        ),
        migrations.AddField(
            model_name='explore',
            name='venue',
            field=models.CharField(default='NULL', max_length=60, verbose_name='Venue'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='dept_name',
            field=models.CharField(max_length=10, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='image',
            field=models.ImageField(upload_to='static/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='contact_name',
            field=models.TextField(verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='contact_num',
            field=models.TextField(verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='link',
            field=models.URLField(verbose_name='Registration Link'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='main_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.main', verbose_name='Event Associated'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='organized_by',
            field=models.CharField(max_length=30, verbose_name='Organized By'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='rewards',
            field=models.TextField(verbose_name='Rewards'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='rules',
            field=models.TextField(verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='main',
            name='conducted_by',
            field=models.CharField(max_length=30, verbose_name='Organized By'),
        ),
        migrations.AlterField(
            model_name='main',
            name='dashboard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.dashboard', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='main',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='main',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='main',
            name='image',
            field=models.ImageField(upload_to='static/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='main',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Title'),
        ),
    ]
