# Generated by Django 3.2.16 on 2022-10-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20221028_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='image',
            field=models.ImageField(default='NULL', upload_to='static/', verbose_name='Image'),
        ),
    ]
