# Generated by Django 3.2.16 on 2022-10-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_explore_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explore',
            name='OD',
            field=models.CharField(choices=[('OD will be Provided', 'OD will be Provided'), ('OD will not be Provided', 'OD will not be Provided')], default='OD will not be Provided', max_length=40, verbose_name='Info about OD'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='participants',
            field=models.CharField(choices=[('Inter-departmental', 'Inter-departmental'), ('Intra-departmental', 'Intra-departmental')], default='Intradepartmental', max_length=40, verbose_name='Inter or Intra'),
        ),
        migrations.AlterField(
            model_name='explore',
            name='participation_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Team size-2', 'Team size-2'), ('Team size-3', 'Team size-3'), ('Team size-4', 'Team size-4'), ('Team size-5', 'Team size-5'), ('Team size-6', 'Team size-6')], default='Individual', max_length=40, verbose_name='Type of Participation'),
        ),
    ]
