# Generated by Django 3.2.16 on 2022-10-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20221028_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='venue',
            field=models.CharField(default='NULL', max_length=60, verbose_name='Venue'),
        ),
    ]
