# Generated by Django 3.2.16 on 2022-10-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_main_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
    ]
