# Generated by Django 3.2.16 on 2022-10-29 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_main_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='explore',
        ),
    ]
