# Generated by Django 3.2.16 on 2022-10-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_delete_explore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='description',
        ),
        migrations.AddField(
            model_name='main',
            name='hover_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Hover Description'),
        ),
    ]
