# Generated by Django 3.2.16 on 2022-10-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20221029_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='contact_name',
            new_name='contact_details',
        ),
        migrations.RemoveField(
            model_name='main',
            name='contact_num',
        ),
    ]
