# Generated by Django 3.2.16 on 2022-10-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20221029_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(default='', max_length=20, verbose_name='club name')),
                ('gs', models.CharField(default='', max_length=20, verbose_name='GS')),
                ('gt', models.CharField(default='', max_length=20, verbose_name='GT')),
                ('js', models.CharField(default='', max_length=20, verbose_name='JS')),
                ('jt', models.CharField(default='', max_length=20, verbose_name='JT')),
                ('gsn', models.CharField(default='', max_length=20, verbose_name='GS Num')),
                ('gtn', models.CharField(default='', max_length=20, verbose_name='GT Num')),
                ('jsn', models.CharField(default='', max_length=20, verbose_name='JS Num')),
                ('jtn', models.CharField(default='', max_length=20, verbose_name='JT Num')),
                ('desc', models.TextField(default='', verbose_name='Description')),
                ('image', models.ImageField(upload_to='static/', verbose_name='Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='image',
        ),
        migrations.AlterField(
            model_name='main',
            name='contact_details',
            field=models.TextField(default='', verbose_name='Contact details'),
        ),
    ]
