# Generated by Django 3.2.16 on 2022-10-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20221029_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
