# Generated by Django 3.2.16 on 2022-11-01 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_waste'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_cl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('venue', models.CharField(max_length=60, verbose_name='Venue')),
                ('image', models.ImageField(upload_to='static/', verbose_name='Image')),
                ('conducted_by', models.CharField(max_length=30, verbose_name='Organized By')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('time', models.CharField(max_length=20, verbose_name='Time')),
                ('event_description', models.TextField(verbose_name='Event Description')),
                ('contact_details', models.TextField(verbose_name='Contact details')),
                ('link', models.URLField(verbose_name='Registration Link')),
                ('clubs', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.clubs', verbose_name='Club')),
            ],
        ),
    ]
