# Generated by Django 3.2.16 on 2022-11-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_event_cl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_cl',
            name='conducted_by',
        ),
        migrations.RemoveField(
            model_name='event_cl',
            name='event_description',
        ),
        migrations.RemoveField(
            model_name='event_cl',
            name='link',
        ),
        migrations.AlterField(
            model_name='clubs',
            name='image',
            field=models.ImageField(upload_to='static/club', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='main',
            name='image',
            field=models.ImageField(upload_to='static/club', verbose_name='Image'),
        ),
    ]
