# Generated by Django 3.2.16 on 2022-11-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20221103_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_events',
            name='image',
            field=models.ImageField(upload_to='static/dept', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='achievers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_event_name', models.CharField(max_length=30, verbose_name='Event Name')),
                ('first', models.CharField(max_length=30, verbose_name='1 Name-regno')),
                ('second', models.CharField(max_length=30, verbose_name='2 Name-regno')),
                ('third', models.CharField(max_length=30, verbose_name='3 Name-regno')),
                ('first_dept', models.CharField(max_length=30, verbose_name='1st Department name')),
                ('second_dept', models.CharField(max_length=30, verbose_name='2nd Department name')),
                ('third_dept', models.CharField(max_length=30, verbose_name='3rd Department name')),
                ('image1', models.ImageField(upload_to='static/ach', verbose_name='Image1')),
                ('image2', models.ImageField(upload_to='static/ach', verbose_name='Image2')),
                ('image3', models.ImageField(upload_to='static/ach', verbose_name='Image3')),
                ('dept', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.dept', verbose_name='Event belongs to')),
            ],
        ),
    ]
