# Generated by Django 3.2.16 on 2022-11-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20221103_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='instagram_link',
            field=models.URLField(default='', verbose_name='Instagram Link'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='whatsapp',
            field=models.URLField(default='', verbose_name='Whatsapp Link'),
        ),
    ]
